defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: Iain Saunders
subtitle: Commercial Analyst and second year Data Science undergrad

# left_side:
#   background_image: "./assets/images/left-background.jpg"
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"

footer:
  copyright_text: "&copy; Iain Saunders"

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: Skills & Offers
    link: /skills-and-offers
    icon: ""

  - text: Contact Me
    link: /contact
    icon: ""

  - text: Curriculum Vitae
    link: /curriculumvitae
    icon: ""

  - text: Blog Posts
    link: /blog
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/in/iainsaun
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/iainsaun
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/
    icon: fab fa-facebook-square

  - name: twitter
    link: https://www.twitter.com/
    icon: fab fa-twitter
